# Port Configuration
server.port=8080
spring.datasource.url=jdbc:mysql://elearning-db.crss2am646ar.ap-south-1.rds.amazonaws.com:3306/elearningdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=Elearning123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true


# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-swallow-size=200MB

# AWS S3 & Lambda Configuration
aws.access-key=
aws.secret-key=
aws.region=ap-south-1
aws.s3.bucket=elearning-lecture-videos-bucket
aws.cloudfront.url=https://d111111abcdef8.cloudfront.net